# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class AttributeMappingDto(BaseModel):
    """
    List of attribute mappings between mapping attributes and (recipient) custom attributes
    """ # noqa: E501
    mapping_attribute_uuid: StrictStr = Field(description="Mapping Attribute UUID", alias="mappingAttributeUuid")
    mapping_attribute_name: StrictStr = Field(description="Mapping Attribute Name", alias="mappingAttributeName")
    custom_attribute_uuid: StrictStr = Field(description="Custom Attribute Uuid", alias="customAttributeUuid")
    custom_attribute_label: StrictStr = Field(description="Custom Attribute Label", alias="customAttributeLabel")
    __properties: ClassVar[List[str]] = ["mappingAttributeUuid", "mappingAttributeName", "customAttributeUuid", "customAttributeLabel"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AttributeMappingDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AttributeMappingDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mappingAttributeUuid": obj.get("mappingAttributeUuid"),
            "mappingAttributeName": obj.get("mappingAttributeName"),
            "customAttributeUuid": obj.get("customAttributeUuid"),
            "customAttributeLabel": obj.get("customAttributeLabel")
        })
        return _obj


