# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyCZERTAINLY.models.group_dto import GroupDto
from pyCZERTAINLY.models.key_association_dto import KeyAssociationDto
from pyCZERTAINLY.models.key_item_detail_dto import KeyItemDetailDto
from pyCZERTAINLY.models.response_attribute_dto import ResponseAttributeDto
from typing import Optional, Set
from typing_extensions import Self

class KeyDetailDto(BaseModel):
    """
    KeyDetailDto
    """ # noqa: E501
    uuid: StrictStr = Field(description="Object identifier")
    name: StrictStr = Field(description="Object Name")
    description: StrictStr = Field(description="Description of the Key")
    creation_time: datetime = Field(description="Creation time of the Key. If the key is discovered from the connector, then it will be returned", alias="creationTime")
    token_profile_uuid: Optional[StrictStr] = Field(default=None, description="UUID of the Token Profile", alias="tokenProfileUuid")
    token_profile_name: Optional[StrictStr] = Field(default=None, description="Name of the Token Profile", alias="tokenProfileName")
    token_instance_uuid: StrictStr = Field(description="Token Instance UUID", alias="tokenInstanceUuid")
    token_instance_name: StrictStr = Field(description="Token Instance Name", alias="tokenInstanceName")
    custom_attributes: Optional[List[ResponseAttributeDto]] = Field(default=None, description="Custom Attributes for the Cryptographic Key", alias="customAttributes")
    attributes: List[ResponseAttributeDto] = Field(description="Attributes for the Cryptographic Key")
    owner: Optional[StrictStr] = Field(default=None, description="Owner of the Key")
    owner_uuid: Optional[StrictStr] = Field(default=None, description="UUID of the owner of the Key", alias="ownerUuid")
    groups: Optional[List[GroupDto]] = Field(default=None, description="Groups associated to the key")
    items: List[KeyItemDetailDto] = Field(description="Key Objects")
    associations: Optional[List[KeyAssociationDto]] = Field(default=None, description="List of associated items")
    __properties: ClassVar[List[str]] = ["uuid", "name", "description", "creationTime", "tokenProfileUuid", "tokenProfileName", "tokenInstanceUuid", "tokenInstanceName", "customAttributes", "attributes", "owner", "ownerUuid", "groups", "items", "associations"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KeyDetailDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in custom_attributes (list)
        _items = []
        if self.custom_attributes:
            for _item_custom_attributes in self.custom_attributes:
                if _item_custom_attributes:
                    _items.append(_item_custom_attributes.to_dict())
            _dict['customAttributes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in attributes (list)
        _items = []
        if self.attributes:
            for _item_attributes in self.attributes:
                if _item_attributes:
                    _items.append(_item_attributes.to_dict())
            _dict['attributes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in groups (list)
        _items = []
        if self.groups:
            for _item_groups in self.groups:
                if _item_groups:
                    _items.append(_item_groups.to_dict())
            _dict['groups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in associations (list)
        _items = []
        if self.associations:
            for _item_associations in self.associations:
                if _item_associations:
                    _items.append(_item_associations.to_dict())
            _dict['associations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KeyDetailDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "creationTime": obj.get("creationTime"),
            "tokenProfileUuid": obj.get("tokenProfileUuid"),
            "tokenProfileName": obj.get("tokenProfileName"),
            "tokenInstanceUuid": obj.get("tokenInstanceUuid"),
            "tokenInstanceName": obj.get("tokenInstanceName"),
            "customAttributes": [ResponseAttributeDto.from_dict(_item) for _item in obj["customAttributes"]] if obj.get("customAttributes") is not None else None,
            "attributes": [ResponseAttributeDto.from_dict(_item) for _item in obj["attributes"]] if obj.get("attributes") is not None else None,
            "owner": obj.get("owner"),
            "ownerUuid": obj.get("ownerUuid"),
            "groups": [GroupDto.from_dict(_item) for _item in obj["groups"]] if obj.get("groups") is not None else None,
            "items": [KeyItemDetailDto.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "associations": [KeyAssociationDto.from_dict(_item) for _item in obj["associations"]] if obj.get("associations") is not None else None
        })
        return _obj


