# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RequestAttributeCallback(BaseModel):
    """
    RequestAttributeCallback
    """ # noqa: E501
    uuid: Optional[StrictStr] = Field(default=None, description="UUID of the Attribute")
    name: StrictStr = Field(description="Name of the Attribute")
    path_variable: Optional[Dict[str, Dict[str, Any]]] = Field(default=None, description="Map of path variables supported by the callback method", alias="pathVariable")
    request_parameter: Optional[Dict[str, Dict[str, Any]]] = Field(default=None, description="Map of the query parameters supported by the callback method", alias="requestParameter")
    body: Optional[Dict[str, Dict[str, Any]]] = Field(default=None, description="Request body for the callback method")
    __properties: ClassVar[List[str]] = ["uuid", "name", "pathVariable", "requestParameter", "body"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RequestAttributeCallback from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RequestAttributeCallback from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "name": obj.get("name"),
            "pathVariable": obj.get("pathVariable"),
            "requestParameter": obj.get("requestParameter"),
            "body": obj.get("body")
        })
        return _obj


