# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.trigger_history_summary_dto import TriggerHistorySummaryDto

class TestTriggerHistorySummaryDto(unittest.TestCase):
    """TriggerHistorySummaryDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TriggerHistorySummaryDto:
        """Test TriggerHistorySummaryDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TriggerHistorySummaryDto`
        """
        model = TriggerHistorySummaryDto()
        if include_optional:
            return TriggerHistorySummaryDto(
                association_resource = 'NONE',
                association_object_uuid = '',
                objects_resource = 'NONE',
                objects_evaluated = 56,
                objects_matched = 56,
                objects_ignored = 56,
                objects = [
                    openapi_client.models.trigger_history_object_summary_dto.TriggerHistoryObjectSummaryDto(
                        object_uuid = '', 
                        reference_object_uuid = '', 
                        matched = True, 
                        ignored = True, 
                        triggers = [
                            openapi_client.models.trigger_history_object_trigger_summary_dto.TriggerHistoryObjectTriggerSummaryDto(
                                trigger_uuid = '', 
                                trigger_name = '', 
                                triggered_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                message = '', 
                                records = [
                                    openapi_client.models.trigger_history_record_dto.TriggerHistoryRecordDto(
                                        message = '', 
                                        condition = openapi_client.models.condition_dto.ConditionDto(
                                            uuid = '7b55ge1c-844f-11dc-a8a3-0242ac120002', 
                                            name = 'Name', 
                                            description = '', 
                                            type = 'checkField', 
                                            resource = 'NONE', 
                                            items = [
                                                openapi_client.models.condition_item_dto.ConditionItemDto(
                                                    field_source = 'meta', 
                                                    field_identifier = '', 
                                                    operator = 'EQUALS', 
                                                    value = openapi_client.models.value.value(), )
                                                ], ), 
                                        execution = openapi_client.models.execution_dto.ExecutionDto(
                                            uuid = '7b55ge1c-844f-11dc-a8a3-0242ac120002', 
                                            name = 'Name', 
                                            description = '', 
                                            type = 'setField', 
                                            resource = 'NONE', 
                                            items = [
                                                openapi_client.models.execution_item_dto.ExecutionItemDto(
                                                    field_source = 'meta', 
                                                    field_identifier = '', 
                                                    data = openapi_client.models.data.data(), )
                                                ], ), )
                                    ], )
                            ], )
                    ]
            )
        else:
            return TriggerHistorySummaryDto(
                association_resource = 'NONE',
                association_object_uuid = '',
                objects_resource = 'NONE',
                objects_evaluated = 56,
                objects_matched = 56,
                objects_ignored = 56,
                objects = [
                    openapi_client.models.trigger_history_object_summary_dto.TriggerHistoryObjectSummaryDto(
                        object_uuid = '', 
                        reference_object_uuid = '', 
                        matched = True, 
                        ignored = True, 
                        triggers = [
                            openapi_client.models.trigger_history_object_trigger_summary_dto.TriggerHistoryObjectTriggerSummaryDto(
                                trigger_uuid = '', 
                                trigger_name = '', 
                                triggered_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                message = '', 
                                records = [
                                    openapi_client.models.trigger_history_record_dto.TriggerHistoryRecordDto(
                                        message = '', 
                                        condition = openapi_client.models.condition_dto.ConditionDto(
                                            uuid = '7b55ge1c-844f-11dc-a8a3-0242ac120002', 
                                            name = 'Name', 
                                            description = '', 
                                            type = 'checkField', 
                                            resource = 'NONE', 
                                            items = [
                                                openapi_client.models.condition_item_dto.ConditionItemDto(
                                                    field_source = 'meta', 
                                                    field_identifier = '', 
                                                    operator = 'EQUALS', 
                                                    value = openapi_client.models.value.value(), )
                                                ], ), 
                                        execution = openapi_client.models.execution_dto.ExecutionDto(
                                            uuid = '7b55ge1c-844f-11dc-a8a3-0242ac120002', 
                                            name = 'Name', 
                                            description = '', 
                                            type = 'setField', 
                                            resource = 'NONE', 
                                            items = [
                                                openapi_client.models.execution_item_dto.ExecutionItemDto(
                                                    field_source = 'meta', 
                                                    field_identifier = '', 
                                                    data = openapi_client.models.data.data(), )
                                                ], ), )
                                    ], )
                            ], )
                    ],
        )
        """

    def testTriggerHistorySummaryDto(self):
        """Test TriggerHistorySummaryDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
