# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyCZERTAINLY.models.notification_response_dto import NotificationResponseDto

class TestNotificationResponseDto(unittest.TestCase):
    """NotificationResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationResponseDto:
        """Test NotificationResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotificationResponseDto`
        """
        model = NotificationResponseDto()
        if include_optional:
            return NotificationResponseDto(
                items_per_page = 56,
                page_number = 56,
                total_pages = 56,
                total_items = 56,
                items = [
                    pyCZERTAINLY.models.notification_dto.NotificationDto(
                        uuid = '', 
                        message = '', 
                        detail = '', 
                        read_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        sent_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        target_object_type = 'NONE', 
                        target_object_identification = [
                            ''
                            ], )
                    ]
            )
        else:
            return NotificationResponseDto(
                items_per_page = 56,
                page_number = 56,
                total_pages = 56,
                total_items = 56,
                items = [
                    pyCZERTAINLY.models.notification_dto.NotificationDto(
                        uuid = '', 
                        message = '', 
                        detail = '', 
                        read_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        sent_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        target_object_type = 'NONE', 
                        target_object_identification = [
                            ''
                            ], )
                    ],
        )
        """

    def testNotificationResponseDto(self):
        """Test NotificationResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
