# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.certificate_update_objects_dto import CertificateUpdateObjectsDto

class TestCertificateUpdateObjectsDto(unittest.TestCase):
    """CertificateUpdateObjectsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CertificateUpdateObjectsDto:
        """Test CertificateUpdateObjectsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CertificateUpdateObjectsDto`
        """
        model = CertificateUpdateObjectsDto()
        if include_optional:
            return CertificateUpdateObjectsDto(
                group_uuids = [
                    ''
                    ],
                owner_uuid = '',
                ra_profile_uuid = '',
                trusted_ca = True
            )
        else:
            return CertificateUpdateObjectsDto(
        )
        """

    def testCertificateUpdateObjectsDto(self):
        """Test CertificateUpdateObjectsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
