# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyCZERTAINLY.api.client_operations_v2_api import ClientOperationsV2Api


class TestClientOperationsV2Api(unittest.TestCase):
    """ClientOperationsV2Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ClientOperationsV2Api()

    def tearDown(self) -> None:
        pass

    def test_issue_certificate(self) -> None:
        """Test case for issue_certificate

        Issue Certificate
        """
        pass

    def test_issue_requested_certificate(self) -> None:
        """Test case for issue_requested_certificate

        Issue existing certificate with status Requested
        """
        pass

    def test_list_issue_certificate_attributes(self) -> None:
        """Test case for list_issue_certificate_attributes

        Get issue Certificate Attributes
        """
        pass

    def test_list_revoke_certificate_attributes(self) -> None:
        """Test case for list_revoke_certificate_attributes

        Get revocation Attributes
        """
        pass

    def test_rekey_certificate(self) -> None:
        """Test case for rekey_certificate

        Rekey Certificate
        """
        pass

    def test_renew_certificate(self) -> None:
        """Test case for renew_certificate

        Renew Certificate
        """
        pass

    def test_revoke_certificate(self) -> None:
        """Test case for revoke_certificate

        Revoke Certificate
        """
        pass

    def test_validate_issue_certificate_attributes(self) -> None:
        """Test case for validate_issue_certificate_attributes

        Validate issue Certificate Attributes
        """
        pass

    def test_validate_revoke_certificate_attributes(self) -> None:
        """Test case for validate_revoke_certificate_attributes

        Validate revocation Attributes
        """
        pass


if __name__ == '__main__':
    unittest.main()
