# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.scep_profile_dto import ScepProfileDto

class TestScepProfileDto(unittest.TestCase):
    """ScepProfileDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScepProfileDto:
        """Test ScepProfileDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScepProfileDto`
        """
        model = ScepProfileDto()
        if include_optional:
            return ScepProfileDto(
                uuid = '7b55ge1c-844f-11dc-a8a3-0242ac120002',
                name = 'Name',
                enabled = True,
                description = 'Sample description',
                ra_profile = openapi_client.models.simplified_ra_profile_dto.SimplifiedRaProfileDto(
                    uuid = '7b55ge1c-844f-11dc-a8a3-0242ac120002', 
                    name = 'Name', 
                    enabled = True, 
                    authority_instance_uuid = '', ),
                include_ca_certificate = True,
                include_ca_certificate_chain = True,
                renew_threshold = 30,
                scep_url = 'https://some-server.com/api/v1/protocols/scep/profile/pkiclient.exe',
                enable_intune = True
            )
        else:
            return ScepProfileDto(
                uuid = '7b55ge1c-844f-11dc-a8a3-0242ac120002',
                name = 'Name',
                enabled = True,
                include_ca_certificate = True,
                include_ca_certificate_chain = True,
        )
        """

    def testScepProfileDto(self):
        """Test ScepProfileDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
