# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.compliance_rule_status import ComplianceRuleStatus

class TestComplianceRuleStatus(unittest.TestCase):
    """ComplianceRuleStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComplianceRuleStatus(self):
        """Test ComplianceRuleStatus"""
        # inst = ComplianceRuleStatus()

if __name__ == '__main__':
    unittest.main()
