# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyCZERTAINLY.api.cmp_profile_management_api import CMPProfileManagementApi


class TestCMPProfileManagementApi(unittest.TestCase):
    """CMPProfileManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CMPProfileManagementApi()

    def tearDown(self) -> None:
        pass

    def test_bulk_delete_cmp_profile(self) -> None:
        """Test case for bulk_delete_cmp_profile

        Delete multiple CMP Profiles
        """
        pass

    def test_bulk_disable_cmp_profile(self) -> None:
        """Test case for bulk_disable_cmp_profile

        Disable multiple CMP Profile
        """
        pass

    def test_bulk_enable_cmp_profile(self) -> None:
        """Test case for bulk_enable_cmp_profile

        Enable multiple CMP Profiles
        """
        pass

    def test_create_cmp_profile(self) -> None:
        """Test case for create_cmp_profile

        Create CMP Profile
        """
        pass

    def test_delete_cmp_profile(self) -> None:
        """Test case for delete_cmp_profile

        Delete CMP Profile
        """
        pass

    def test_disable_cmp_profile(self) -> None:
        """Test case for disable_cmp_profile

        Disable CMP Profile
        """
        pass

    def test_edit_cmp_profile(self) -> None:
        """Test case for edit_cmp_profile

        Edit CMP Profile
        """
        pass

    def test_enable_cmp_profile(self) -> None:
        """Test case for enable_cmp_profile

        Enable CMP Profile
        """
        pass

    def test_force_delete_cmp_profiles(self) -> None:
        """Test case for force_delete_cmp_profiles

        Force delete multiple CMP Profiles
        """
        pass

    def test_get_cmp_profile(self) -> None:
        """Test case for get_cmp_profile

        Get details of CMP Profile
        """
        pass

    def test_list_cmp_profiles(self) -> None:
        """Test case for list_cmp_profiles

        Get list of CMP Profiles
        """
        pass

    def test_list_cmp_signing_certificates(self) -> None:
        """Test case for list_cmp_signing_certificates

        Get list of certificates eligible for signing of CMP responses
        """
        pass

    def test_update_ra_profile1(self) -> None:
        """Test case for update_ra_profile1

        Update RA Profile for CMP Profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
