# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.update_execution_request_dto import UpdateExecutionRequestDto

class TestUpdateExecutionRequestDto(unittest.TestCase):
    """UpdateExecutionRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateExecutionRequestDto:
        """Test UpdateExecutionRequestDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateExecutionRequestDto`
        """
        model = UpdateExecutionRequestDto()
        if include_optional:
            return UpdateExecutionRequestDto(
                description = '',
                items = [
                    openapi_client.models.execution_item_request_dto.ExecutionItemRequestDto(
                        field_source = 'meta', 
                        field_identifier = '', 
                        data = openapi_client.models.data.data(), )
                    ]
            )
        else:
            return UpdateExecutionRequestDto(
                items = [
                    openapi_client.models.execution_item_request_dto.ExecutionItemRequestDto(
                        field_source = 'meta', 
                        field_identifier = '', 
                        data = openapi_client.models.data.data(), )
                    ],
        )
        """

    def testUpdateExecutionRequestDto(self):
        """Test UpdateExecutionRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
