# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.key_format import KeyFormat

class TestKeyFormat(unittest.TestCase):
    """KeyFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKeyFormat(self):
        """Test KeyFormat"""
        # inst = KeyFormat()

if __name__ == '__main__':
    unittest.main()
