# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.cryptographic_operations_controller_api import CryptographicOperationsControllerApi


class TestCryptographicOperationsControllerApi(unittest.TestCase):
    """CryptographicOperationsControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CryptographicOperationsControllerApi()

    def tearDown(self) -> None:
        pass

    def test_decrypt_data(self) -> None:
        """Test case for decrypt_data

        Decrypt data using a Key
        """
        pass

    def test_encrypt_data(self) -> None:
        """Test case for encrypt_data

        Encrypt data using a Key
        """
        pass

    def test_list_cipher_attributes(self) -> None:
        """Test case for list_cipher_attributes

        List of cipher Attributes
        """
        pass

    def test_list_random_attributes(self) -> None:
        """Test case for list_random_attributes

        List of random generator Attributes
        """
        pass

    def test_list_signature_attributes(self) -> None:
        """Test case for list_signature_attributes

        List of signature Attributes
        """
        pass

    def test_random_data(self) -> None:
        """Test case for random_data

        Generate random data
        """
        pass

    def test_sign_data(self) -> None:
        """Test case for sign_data

        Sign data using a Key
        """
        pass

    def test_verify_data(self) -> None:
        """Test case for verify_data

        Verify data using a Key
        """
        pass


if __name__ == '__main__':
    unittest.main()
