# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyCZERTAINLY.models.filter_condition_operator import FilterConditionOperator

class TestFilterConditionOperator(unittest.TestCase):
    """FilterConditionOperator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterConditionOperator(self):
        """Test FilterConditionOperator"""
        # inst = FilterConditionOperator()

if __name__ == '__main__':
    unittest.main()
