# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyCZERTAINLY.models.attribute_value_target import AttributeValueTarget

class TestAttributeValueTarget(unittest.TestCase):
    """AttributeValueTarget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttributeValueTarget(self):
        """Test AttributeValueTarget"""
        # inst = AttributeValueTarget()

if __name__ == '__main__':
    unittest.main()
