# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyCZERTAINLY.api.approval_profile_inventory_api import ApprovalProfileInventoryApi


class TestApprovalProfileInventoryApi(unittest.TestCase):
    """ApprovalProfileInventoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApprovalProfileInventoryApi()

    def tearDown(self) -> None:
        pass

    def test_create_approval_profile(self) -> None:
        """Test case for create_approval_profile

        Create a Approval profile
        """
        pass

    def test_delete_approval_profile(self) -> None:
        """Test case for delete_approval_profile

        Delete an approval profile
        """
        pass

    def test_disable_approval_profile(self) -> None:
        """Test case for disable_approval_profile

        Disabling of Approval profile
        """
        pass

    def test_edit_approval_profile(self) -> None:
        """Test case for edit_approval_profile

        Edit an Approval profile
        """
        pass

    def test_enable_approval_profile(self) -> None:
        """Test case for enable_approval_profile

        Enabling of Approval profile
        """
        pass

    def test_get_approval_profile(self) -> None:
        """Test case for get_approval_profile

        Get Approval Profile Details
        """
        pass

    def test_list_approval_profiles(self) -> None:
        """Test case for list_approval_profiles

        List Approval Profiles
        """
        pass


if __name__ == '__main__':
    unittest.main()
