# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.connector_management_api import ConnectorManagementApi


class TestConnectorManagementApi(unittest.TestCase):
    """ConnectorManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectorManagementApi()

    def tearDown(self) -> None:
        pass

    def test_approve(self) -> None:
        """Test case for approve

        Approve a Connector
        """
        pass

    def test_bulk_approve(self) -> None:
        """Test case for bulk_approve

        Approve multiple Connector
        """
        pass

    def test_bulk_delete_connector(self) -> None:
        """Test case for bulk_delete_connector

        Delete multiple Connectors
        """
        pass

    def test_bulk_reconnect(self) -> None:
        """Test case for bulk_reconnect

        Reconnect multiple Connectors
        """
        pass

    def test_check_health(self) -> None:
        """Test case for check_health

        Check Health of a Connector
        """
        pass

    def test_connect(self) -> None:
        """Test case for connect

        Connect to a Connector
        """
        pass

    def test_create_connector(self) -> None:
        """Test case for create_connector

        Create a new Connector
        """
        pass

    def test_delete_connector(self) -> None:
        """Test case for delete_connector

        Delete a Connector
        """
        pass

    def test_edit_connector(self) -> None:
        """Test case for edit_connector

        Edit a Connector
        """
        pass

    def test_force_delete_connector(self) -> None:
        """Test case for force_delete_connector

        Force Delete multiple Connectors
        """
        pass

    def test_get_attributes(self) -> None:
        """Test case for get_attributes

        Get Attributes from a Connector
        """
        pass

    def test_get_attributes_all(self) -> None:
        """Test case for get_attributes_all

        Get attributes of all Function Groups
        """
        pass

    def test_get_connector(self) -> None:
        """Test case for get_connector

        Get details of a Connector
        """
        pass

    def test_list_connectors(self) -> None:
        """Test case for list_connectors

        List Connectors by Function Group and Kind
        """
        pass

    def test_reconnect(self) -> None:
        """Test case for reconnect

        Reconnect to a Connector
        """
        pass

    def test_validate_attributes(self) -> None:
        """Test case for validate_attributes

        Validate Attributes
        """
        pass


if __name__ == '__main__':
    unittest.main()
