# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.attribute_content_type import AttributeContentType
from openapi_client.models.attribute_type import AttributeType
from openapi_client.models.base_attribute_content_dto import BaseAttributeContentDto
from openapi_client.models.metadata_attribute_properties import MetadataAttributeProperties
from typing import Optional, Set
from typing_extensions import Self

class MetadataAttribute(BaseModel):
    """
    Info attribute contains content that is for metadata. Its content can not be edited and is not send in requests to store.
    """ # noqa: E501
    uuid: StrictStr = Field(description="UUID of the Attribute for unique identification")
    name: StrictStr = Field(description="Name of the Attribute that is used for identification")
    description: Optional[StrictStr] = Field(default=None, description="Optional description of the Attribute, should contain helper text on what is expected")
    content: List[BaseAttributeContentDto] = Field(description="Content of the Attribute")
    type: AttributeType
    content_type: AttributeContentType = Field(alias="contentType")
    properties: MetadataAttributeProperties
    __properties: ClassVar[List[str]] = ["uuid", "name", "description", "content", "type", "contentType", "properties"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MetadataAttribute from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in content (list)
        _items = []
        if self.content:
            for _item_content in self.content:
                if _item_content:
                    _items.append(_item_content.to_dict())
            _dict['content'] = _items
        # override the default output from pydantic by calling `to_dict()` of properties
        if self.properties:
            _dict['properties'] = self.properties.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MetadataAttribute from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "content": [BaseAttributeContentDto.from_dict(_item) for _item in obj["content"]] if obj.get("content") is not None else None,
            "type": obj.get("type"),
            "contentType": obj.get("contentType"),
            "properties": MetadataAttributeProperties.from_dict(obj["properties"]) if obj.get("properties") is not None else None
        })
        return _obj


