# coding: utf-8

"""
    CZERTAINLY Core API

    REST API for CZERTAINLY Core

    The version of the OpenAPI document: 2.13.2-SNAPSHOT
    Contact: info@czertainly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from openapi_client.models.request_attribute_dto import RequestAttributeDto
from openapi_client.models.signature_request_data import SignatureRequestData
from typing import Optional, Set
from typing_extensions import Self

class VerifyDataRequestDto(BaseModel):
    """
    VerifyDataRequestDto
    """ # noqa: E501
    signature_attributes: List[RequestAttributeDto] = Field(description="List of signature Attributes", alias="signatureAttributes")
    data: List[SignatureRequestData] = Field(description="Data to be signed")
    signatures: List[SignatureRequestData] = Field(description="Signatures to verify")
    __properties: ClassVar[List[str]] = ["signatureAttributes", "data", "signatures"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VerifyDataRequestDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in signature_attributes (list)
        _items = []
        if self.signature_attributes:
            for _item_signature_attributes in self.signature_attributes:
                if _item_signature_attributes:
                    _items.append(_item_signature_attributes.to_dict())
            _dict['signatureAttributes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item_data in self.data:
                if _item_data:
                    _items.append(_item_data.to_dict())
            _dict['data'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in signatures (list)
        _items = []
        if self.signatures:
            for _item_signatures in self.signatures:
                if _item_signatures:
                    _items.append(_item_signatures.to_dict())
            _dict['signatures'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VerifyDataRequestDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "signatureAttributes": [RequestAttributeDto.from_dict(_item) for _item in obj["signatureAttributes"]] if obj.get("signatureAttributes") is not None else None,
            "data": [SignatureRequestData.from_dict(_item) for _item in obj["data"]] if obj.get("data") is not None else None,
            "signatures": [SignatureRequestData.from_dict(_item) for _item in obj["signatures"]] if obj.get("signatures") is not None else None
        })
        return _obj


